name = "decode"
version = "0.5.0"
description = "Ergonomic dynamic decoders for Gleam!"
licences = ["Apache-2.0"]
repository = { type = "github", user = "lpil", repo = "decode" }
links = [{ title = "Sponsor", href = "https://github.com/sponsors/lpil" }]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
